/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class za_co_facegroup_zar_License */

#ifndef _Included_za_co_facegroup_zar_License
#define _Included_za_co_facegroup_zar_License
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     za_co_facegroup_zar_License
 * Method:    loadlicense
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_za_co_facegroup_zar_License_loadlicense
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     za_co_facegroup_zar_License
 * Method:    deserialize
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_za_co_facegroup_zar_License_deserialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
